In [4]:
import math
import torch
from torch import nn
from d2l import torch as d2l

In [5]:
def masked_softmax(X, valid_lens):
    print(valid_lens.shape)
    if valid_lens is None:
        return nn.functional.softmax(X, dim=-1)
    else:
        shape = X.shape
        print("valid_lens.dim is", valid_lens.dim())
        if valid_lens.dim() == 1:
            valid_lens = torch.repeat_interleave(valid_lens, shape[1]) 
        else:
            valid_lens = valid_lens.reshape(-1)
        print("X in the mask has a shape of ", X.reshape(-1, shape[-1]).shape)
        print("valid_lens has a shape of ", valid_lens.shape)
        X = d2l.sequence_mask(X.reshape(-1, shape[-1]), valid_lens, 
                              value=-1e6)
        return nn.functional.softmax(X.reshape(shape), dim=-1)

In [7]:
a = torch.arange(0, 4)
a

tensor([0, 1, 2, 3])

In [8]:
# Example of using torch.repeat_interleave()
torch.repeat_interleave(a, a.shape[0]), a.repeat(4)

(tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]),
 tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [9]:
masked_softmax(torch.rand(2, 2, 4), torch.tensor([2, 3]))

torch.Size([2])
valid_lens.dim is 1
X in the mask has a shape of  torch.Size([4, 4])
valid_lens has a shape of  torch.Size([4])


tensor([[[0.5415, 0.4585, 0.0000, 0.0000],
         [0.4678, 0.5322, 0.0000, 0.0000]],

        [[0.4710, 0.2766, 0.2524, 0.0000],
         [0.3012, 0.3972, 0.3016, 0.0000]]])