In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [2]:
def dropout_layer(X, dropout):
    """
    Implements a custom Dropout layer that randomly sets a portion of the input tensor elements to zero to prevent overfitting.


    Parameters:
    X (torch.Tensor): A vector/matrix 
    dropout (float or torch.Tensor): a value representing dropout probability ranging [0, 1]. 
        Higher values drop more elements, 1 drops all elements, and 0 performs no dropout

    Returns:
    (torch.Tensor): parameter X after dropout operation
    """
    assert 0 <= dropout <= 1
    if dropout == 1:
        return torch.zeros_like(X)
    if dropout == 0:
        return X

    # Generate a mask from a normal distribution where values greater than dropout are 1, else 0
    mask = (torch.randn(X.shape) > dropout).float()

    # Scale the tensor by dividing by (1.0 - dropout) to maintain the expected value of activations
    return mask * X / (1.0 - dropout)

In [3]:
X = torch.arange(16, dtype=torch.float32).reshape((2, 8))
print(X)
print(dropout_layer(X, 0.))
print(dropout_layer(X, 0.5))
print(dropout_layer(X, 1.))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  2.,  4.,  0.,  8., 10.,  0., 14.],
        [ 0., 18.,  0.,  0.,  0.,  0., 28.,  0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
